finalize

diff --git a/initrd/init b/initrd/init
--- a/initrd/init
+++ b/initrd/init
@@ -65,14 +65,16 @@ EOF
 	fi
 
 	# Hide bootctrl from VINTF manifest if we don't set up virtual A/B
-	if [ ! "$(cat /proc/cmdline | grep androidboot.slot_suffix)" ]; then
+	if ! grep androidboot.slot_suffix /proc/cmdline; then
 		cat <<"EOF"
 # WARNING: The system is not prepared with Virtual A/B, 
 # so OTA Update will not be supported
 EOF
-		echo '<?xml version="1.0" encoding="utf-8"?>' >/tmp/fakeboot.xml
-		echo '<manifest version="1.0" type="device">' >>/tmp/fakeboot.xml
-		echo '</manifest>' >>/tmp/fakeboot.xml
+		cat <<'EOF' >/tmp/fakeboot.xml
+<?xml version="1.0" encoding="utf-8"?>
+<manifest version="1.0" type="device">
+</manifest>
+EOF
 		mount --bind /tmp/fakeboot.xml system/vendor/etc/vintf/manifest/android.hardware.boot@1.2.xml
 	fi
 }
@@ -240,17 +242,17 @@ find_sysroot() {
 	echo "If it took too long to detect, reboot and check your installation folder"
 	echo ""
 
-	local iter=0
-	while [ $iter -lt $1 ]; do
+	for _ in $(seq 0 $1); do
 		for dev in /dev/[hmnsvx][dmrv][0-9a-z]*; do
-			check_sysroot $dev && return 0
+			test -e $dev &&
+				check_sysroot $dev &&
+				return 0
 		done
 		sleep 5
-		iter=$((iter + 1))
 		echo -n .
 	done
 
-	echo "Detecting failed after $iter iterations!"
+	echo "Detecting failed after $1 iterations!"
 	echo ""
 
 	return 1
@@ -329,10 +331,8 @@ setup_ab_loops() {
 	ln -s $(setup_loop /mnt/$SRC/initrd_b.img) /dev/block/by-name/initrd_b
 	ln -s $(setup_loop /mnt/$SRC/kernel_a) /dev/block/by-name/kernel_a
 	ln -s $(setup_loop /mnt/$SRC/kernel_b) /dev/block/by-name/kernel_b
-	# ln -s $(setup_loop /mnt/$SRC/misc.img) /dev/block/by-name/misc
+	ln -s $(setup_loop /mnt/$SRC/misc.img) /dev/block/by-name/misc
 }
-
-cvar() { echo "$1" | cut -f 2 -d "="; }
 
 echo "Detecting Android-x86..."
 echo ""
@@ -341,15 +341,16 @@ echo ""
 
 [ -z "$SRC" ] && [ -n "$BOOT_IMAGE" ] && SRC=$(dirname "$BOOT_IMAGE")
 
-while read -r c; do
+# shellcheck disable=SC2013
+for c in $(cat /proc/cmdline); do
 	case "$c" in
-	iso-scan/filename=*) iso=$(cvar "$c") ;;
-	androidboot.slot_suffix=*) SLOT=$(cvar "$c") ;;
-	androidboot.efidisk=*) EFIDISK=$(find_device "$(cvar "$c")") ;;
-	androidboot.efidir=*) EFIDIR=$(cvar "$c") ;;
+	iso-scan/filename=*) iso=${c##*=} ;;
+	androidboot.slot_suffix=*) SLOT=${c##*=} ;;
+	androidboot.efidisk=*) EFIDISK=$(find_device "${c##*=}") ;;
+	androidboot.efidir=*) EFIDIR=${c##*=} ;;
 	*) ;;
 	esac
-done </proc/cmdline
+done
 
 ROOT=$(find_device "$ROOT")
 
@@ -374,9 +375,8 @@ if ! grep 'sse4_2' /proc/cpuinfo 1>/dev/null; then
 fi
 
 # load scripts
-# shellcheck disable=SC2045
-for s in $(ls /scripts/* /src/scripts/*); do
-	# shellcheck disable=SC1090
+# shellcheck disable=SC1090
+for s in /scripts/* /mnt/"$SRC"/scripts/*; do
 	test -e "$s" && source "$s"
 done
 
@@ -385,7 +385,6 @@ process_fstab
 # shellcheck disable=SC2164
 cd /android
 
-# ln -s mnt/$SRC /src
 ln -s android/system /
 ln -s ../system/lib/firmware ../system/lib/modules /lib
 mkdir -p /lib/modules
@@ -401,10 +400,6 @@ fi
 
 bliss_feature
 device_information
-
-# if [ -n "$INSTALL" ]; then
-# 	zcat /src/install.img | ( cd /; cpio -iud > /dev/null )
-# fi
 
 link_fstab
 
